/*	Benjamin DELPY `gentilkiwi`
	https://blog.gentilkiwi.com
	benjamin@gentilkiwi.com
	Licence : https://creativecommons.org/licenses/by/4.0/
*/
#pragma once
#include <windows.h>
#include "ftdi/ftd2xx.h"

#ifdef __cplusplus
extern "C" {
#endif

#define FT_FAST_FAIL(c) \
	{ \
		status = c; \
		if(!FT_SUCCESS(status)) \
			goto FT_FAIL; \
	}

#define KFTDI_MPSSE_MAX_FREQUENCY_WITH_DIV		(6000000)
#define KFTDI_MPSSE_MAX_FREQUENCY_WITHOUT_DIV	(30000000)


#define KFTDI_MPSSE_DATA_SHIFTING_CLK_EDGE_POS  (0)
#define KFTDI_MPSSE_DATA_SHIFTING_CLK_EDGE_NEG  (1)

#define KFTDI_MPSSE_DATA_SHIFTING_OUT_CLK_EDGE_POS	(KFTDI_MPSSE_DATA_SHIFTING_CLK_EDGE_POS << 0)
#define KFTDI_MPSSE_DATA_SHIFTING_OUT_CLK_EDGE_NEG	(KFTDI_MPSSE_DATA_SHIFTING_CLK_EDGE_NEG << 0)
#define KFTDI_MPSSE_DATA_SHIFTING_BYTE_MODE			(0 << 1)
#define KFTDI_MPSSE_DATA_SHIFTING_BIT_MODE			(1 << 1)
#define KFTDI_MPSSE_DATA_SHIFTING_IN_CLK_EDGE_POS	(KFTDI_MPSSE_DATA_SHIFTING_CLK_EDGE_POS << 2)
#define KFTDI_MPSSE_DATA_SHIFTING_IN_CLK_EDGE_NEG	(KFTDI_MPSSE_DATA_SHIFTING_CLK_EDGE_NEG << 2)
#define KFTDI_MPSSE_DATA_SHIFTING_MSB_MODE			(0 << 3)
#define KFTDI_MPSSE_DATA_SHIFTING_LSB_MODE			(1 << 3)
#define KFTDI_MPSSE_DATA_SHIFTING_DO_NOWRITE		(0 << 4)
#define KFTDI_MPSSE_DATA_SHIFTING_DO_WRITE			(1 << 4)
#define KFTDI_MPSSE_DATA_SHIFTING_DI_NOREAD			(0 << 5)
#define KFTDI_MPSSE_DATA_SHIFTING_DI_READ			(1 << 5)
#define KFTDI_MPSSE_DATA_SHIFTING_CS_NOWRITE		(0 << 6)
#define KFTDI_MPSSE_DATA_SHIFTING_CS_WRITE			(1 << 6)


#define KFTDI_MPSSE_GPIO_WRITE			(0 << 0)
#define KFTDI_MPSSE_GPIO_READ			(1 << 0)
#define KFTDI_MPSSE_GPIO_LOW_BYTE		(0 << 1)
#define KFTDI_MPSSE_GPIO_HIGH_BYTE		(1 << 1)

#define KFTDI_MPSSE_CMD_GPIO_WRITE_AD			(0x80 | KFTDI_MPSSE_GPIO_LOW_BYTE | KFTDI_MPSSE_GPIO_WRITE)		// 0x80
#define KFTDI_MPSSE_CMD_GPIO_READ_AD			(0x80 | KFTDI_MPSSE_GPIO_LOW_BYTE | KFTDI_MPSSE_GPIO_READ)		// 0x81
#define KFTDI_MPSSE_CMD_GPIO_WRITE_AC			(0x80 | KFTDI_MPSSE_GPIO_HIGH_BYTE | KFTDI_MPSSE_GPIO_WRITE)	// 0x82
#define KFTDI_MPSSE_CMD_GPIO_READ_AC			(0x80 | KFTDI_MPSSE_GPIO_HIGH_BYTE | KFTDI_MPSSE_GPIO_READ)		// 0x83
#define KFTDI_MPSSE_CMD_LOOPBACK_ENABLE			(0x84)
#define KFTDI_MPSSE_CMD_LOOPBACK_DISABLE		(0x85)
#define KFTDI_MPSSE_CMD_SET_CLOCK_DIVISOR		(0x86)
#define KFTDI_MPSSE_CMD_SEND_IMMEDIATE			(0x87)
#define KFTDI_MPSSE_CMD_WAIT_ON_IO_HIGH			(0x88)
#define KFTDI_MPSSE_CMD_WAIT_ON_IO_LOW			(0x89)
#define KFTDI_MPSSE_CMD_DISABLE_CLK_DIV5		(0x8a)
#define KFTDI_MPSSE_CMD_ENABLE_CLK_DIV5			(0x8b)
#define KFTDI_MPSSE_CMD_ENABLE_3PHASE_CLOCKING	(0x8c)
#define KFTDI_MPSSE_CMD_DISABLE_3PHASE_CLOCKING	(0x8d)
//#define KFTDI_MPSSE_CMD_	(0x8e)
//#define KFTDI_MPSSE_CMD_	(0x8f)
//#define KFTDI_MPSSE_CMD_	(0x94)
//#define KFTDI_MPSSE_CMD_	(0x95)
//#define KFTDI_MPSSE_CMD_	(0x96)
//#define KFTDI_MPSSE_CMD_	(0x97)
//#define KFTDI_MPSSE_CMD_	(0x98) -> (0x9c)
//#define KFTDI_MPSSE_CMD_	(0x99) -> (0x9d)
//#define KFTDI_MPSSE_CMD_	(0x9c)
//#define KFTDI_MPSSE_CMD_	(0x9d)
#define KFTDI_MPSSE_CMD_ENABLE_DRIVE_ONLY_ZERO	(0x9e)

typedef struct _KFTDI_MPSSE_SPI_HANDLE {
	FT_HANDLE ftHandle;
	BYTE PinDirAD;
	BYTE PinValAD;
	BYTE PinDirAC;
	BYTE PinValAC;
	BYTE Options;
} KFTDI_MPSSE_SPI_HANDLE, * PKFTDI_MPSSE_SPI_HANDLE;

#define PIN_INPUT		0
#define PIN_OUTPUT		1
#define PIN_HIGH		1
#define PIN_LOW			0
#define PIN_DIR(n, d)	(d << n)
#define PIN_VALUE(n, v)	(v << n)
FT_STATUS KFTDI_MPSSE_SPI_GPIO_AD_SetPinDirValue(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, BYTE Pin, BYTE Dir, BYTE Value);
FT_STATUS KFTDI_MPSSE_SPI_GPIO_AC_SetPinDirValue(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, BYTE Pin, BYTE Dir, BYTE Value);

FT_STATUS KFTDI_MPSSE_SPI_GPIO_AD_GetPins(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, BYTE* pPins);
FT_STATUS KFTDI_MPSSE_SPI_GPIO_AD_GetPin(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, BYTE Pin, BYTE* pValue);
FT_STATUS KFTDI_MPSSE_SPI_GPIO_AC_GetPins(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, BYTE* pPins);
FT_STATUS KFTDI_MPSSE_SPI_GPIO_AC_GetPin(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, BYTE Pin, BYTE* pValue);

#define PIN_SPI_CLK		0
#define PIN_SPI_MOSI	1
#define PIN_SPI_MISO	2
#define PIN_SPI_CS		3

#define KFTDI_MPSSE_SPI_MODE_0		(KFTDI_MPSSE_DATA_SHIFTING_OUT_CLK_EDGE_NEG | KFTDI_MPSSE_DATA_SHIFTING_IN_CLK_EDGE_POS)

#define KFTDI_MPSSE_SPI_MODE_MSB	KFTDI_MPSSE_DATA_SHIFTING_MSB_MODE
#define KFTDI_MPSSE_SPI_MODE_LSB	KFTDI_MPSSE_DATA_SHIFTING_LSB_MODE

#define KFTDI_MPSSE_SPI_MODE_BYTE	KFTDI_MPSSE_DATA_SHIFTING_BYTE_MODE
#define KFTDI_MPSSE_SPI_MODE_BITS	KFTDI_MPSSE_DATA_SHIFTING_BIT_MODE

FT_STATUS KFTDI_MPSSE_SPI_Open(int deviceNumber, BYTE SpiMode, DWORD Frequency, PKFTDI_MPSSE_SPI_HANDLE pKFTDI);
#define KFTDI_MPSSE_SPI_Close(handle)   FT_Close((handle)->ftHandle)
FT_STATUS KFTDI_MPSSE_SPI_SetFrequency(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, DWORD Frequency);
FT_STATUS KFTDI_MPSSE_SPI_DataShift(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, const BYTE* pcbOutData, BYTE* pbInData, WORD szData);
FT_STATUS KFTDI_MPSSE_SPI_DataShiftEx(PKFTDI_MPSSE_SPI_HANDLE pKFTDI, const BYTE* pcbOutData, BYTE* pbInData, DWORD dwSize);

#define KFTDI_MPSSE_SPI_CS_HIGH(handle)										KFTDI_MPSSE_SPI_GPIO_AD_SetPinDirValue(handle, PIN_SPI_CS, PIN_OUTPUT, PIN_HIGH)
#define KFTDI_MPSSE_SPI_CS_LOW(handle)										KFTDI_MPSSE_SPI_GPIO_AD_SetPinDirValue(handle, PIN_SPI_CS, PIN_OUTPUT, PIN_LOW)

#define KFTDI_MPSSE_SPI_WRITE(handle, pcbOutData, szData)					KFTDI_MPSSE_SPI_DataShift(handle, pcbOutData, NULL, szData)
#define KFTDI_MPSSE_SPI_READ(handle, pbInData, szData)						KFTDI_MPSSE_SPI_DataShift(handle, NULL, pbInData, szData)
#define KFTDI_MPSSE_SPI_WRITE_READ(handle, pcbOutData, pbInData, szData)	KFTDI_MPSSE_SPI_DataShift(handle, pcbOutData, pbInData, szData)

#define KFTDI_MPSSE_SPI_WRITE_EX(handle, pcbOutData, szData)				KFTDI_MPSSE_SPI_DataShiftEx(handle, pcbOutData, NULL, szData)
#define KFTDI_MPSSE_SPI_READ_EX(handle, pbInData, szData)					KFTDI_MPSSE_SPI_DataShiftEx(handle, NULL, pbInData, szData)
#define KFTDI_MPSSE_SPI_WRITE_READ_EX(handle, pcbOutData, pbInData, szData)	KFTDI_MPSSE_SPI_DataShiftEx(handle, pcbOutData, pbInData, szData)

#ifdef __cplusplus
}
#endif
